apiVersion: v1
kind: Pod                                            
metadata:
  name: flask
  labels:
    app: flask-pod                           
spec:                                                
  containers:
    - image: ndxlegends/flask-test:first
      name: flask                              
      ports:
        - containerPort: 5000
      env:
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: test-secret
              key: GOOGLE_CLIENT_SECRET