apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  GOOGLE_CLIENT_ID: MTQwOTUwMDc1NzItdmloYTE4ZjU2NXQwaGM1bXN1ZWpobm03bXB1NDg4NnQuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20=
  GOOGLE_CLIENT_SECRET: R09DU1BYLTBKdUY1N21mMkNmZFh5VnM1RnQzTWVIUGVyc3U=